services:
  - type: web
    name: sih-ocr-backend
    env: python
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn ocr_service:app --host 0.0.0.0 --port $PORT
    plan: free

